models/LabsStudents.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use app\behaviors\FileUploadBehavior;
use yii\helpers\ArrayHelper;


/**
 * This is the model class for table "labs_students".
 *
 * @property integer $id
 * @property integer $labs_id
 * @property integer $student_id
 * @property string $description
 * @property string $file
 * @property integer $points
 * @property integer $create_at
 * @property integer $update_at
 *
 * @property Students $student
 * @property Labs $labs
 */
class LabsStudents extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'labs_students';
    }

    /**
     * @inheritdoc
     */
    public $attachFile;

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['create_at', 'update_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['update_at'],
                ],
            ],
            'fileUpload' => [
                'class' => FileUploadBehavior::className(),
                'image' => 'attachFile',
                'image_attribute' => 'file',
                'fileName' => 'rand',
                'deleteFile' => true,
                'path' => '/web/uploads/labs_students/',
                //'resize'=>['height'=>300],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['labs_id', 'student_id'], 'required'],
            [['description'], 'string'],
            [['attachFile'], 'file', 'extensions'=>'jpg, jpeg, png, doc, docx, xls, xlsx, ppt, pptx, rar, zip, txt, odt, pdf, djvu', 'skipOnEmpty'=>true],
            [['labs_id', 'student_id', 'points', 'create_at', 'update_at'], 'integer'],
            [['points'], 'validatePoints', 'on' => 'update'],
            [['file'], 'string', 'max' => 256]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'labs_id' => 'Лабораторная работа',
            'student_id' => 'Студент',
            'description' => 'Описание',
            'file' => 'файл',
            'attachFile' => 'файл',
            'points' => 'Статус',
            'create_at' => 'Дата добавления',
            'update_at' => 'Дата редактирования',
        ];
    }

    public function validatePoints($attribute, $params)
    {
        $value = (int)$this->getAttribute($attribute);
        if ($value != 0 AND ($value < $this->labs->min_point OR $value > $this->labs->max_point)) {
            $this->addError($attribute, 'Если работа принимается, то она должна оцениваться минимум ' . $this->labs->min_point . ' баллами и максимум ' . $this->labs->max_point . ' баллами!');
            return false;
        }
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudent()
    {
        return $this->hasOne(Students::className(), ['user_id' => 'student_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLabs()
    {
        return $this->hasOne(Labs::className(), ['id' => 'labs_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public static function getLabsAvailableSender()
    {
        $labs = ArrayHelper::map(Labs::find()->with('labsStudents')->where('group_id = :group', [':group' => Yii::$app->user->identity->profile->group->id])->all(), 'id', 'title');
        //var_dump(Yii::$app->user->identity->profile);
        //var_dump($labs);die;
        $result = array();
        foreach($labs as $key => $value)
        {
            $labsStudentsId = LabsStudents::find()->where('labs_id = :lab AND student_id = :student', [':lab' => $key, ':student' => Yii::$app->user->id])->all();
            if(!empty($labsStudentsId))
                continue;
            else
                $result[$key] = $value;
        }
        return $result;
    }

    /** @inheritdoc */
    public function sendNotification()
    {
        Yii::$app->mailer->compose('labs/success', ['lab' => $this])
            ->setFrom('admin@kafedra.dev')
            ->setTo($this->student->user->email)
            ->setSubject('Ваша лабораторная работа принята')
            ->send();
    }
}

controllers/LabsStudentsController.php
<?php

namespace app\controllers;

use app\models\TeacherSubjectGroups;
use Yii;
use app\models\LabsStudents;
use app\models\search\LabsStudentsSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * LabsStudentsController implements the CRUD actions for LabsStudents model.
 */
class LabsStudentsController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all LabsStudents models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new LabsStudentsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        if(Yii::$app->user->can('student'))
            $dataProvider->query->andWhere('student_id = :student', [':student' => Yii::$app->user->id]);
        if(Yii::$app->user->can('teacher'))
            $dataProvider->query->andWhere('teacher_subject_branch.id = labs.tsg_id AND teacher_subject_branch.teacher_id = :teacher', [':teacher' => Yii::$app->user->id]);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single LabsStudents model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new LabsStudents model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new LabsStudents();
        if(!Yii::$app->user->can('student'))
            throw new HttpException(403, 'Только студенты могут отправлять лабораторные работы на проверку');

        if ($model->load(Yii::$app->request->post())) {
            $model->student_id = Yii::$app->user->id;
            $model->points = 0;
            if($model->save()){
                Yii::$app->session->setFlash('success', 'Работа отправлена');
                return $this->redirect(['index']);
            }
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing LabsStudents model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->setScenario('update');
        if(Yii::$app->user->can('student') AND $model->student_id != Yii::$app->user->id) {
            throw new HttpException(403, 'Нельзя редактировать чужие работы');
        }
        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->user->can('student')) {
                $model->points = $model->getOldAttribute('points');
            }
            if (Yii::$app->user->can('teacher')) {
                $tsg = TeacherSubjectGroups::find()->innerJoinWith(['subjectBranches', 'subjectBranches.branch', 'subjectBranches.branch.groups'])->where('teacher_subject_branch.id = :tsg AND teacher_subject_branch.teacher_id = :teacher AND groups.id = :group', [':teacher' => Yii::$app->user->id, ':group' => $model->labs->group_id, ':tsg' => $model->labs->tsg_id]);
            }
            if ((Yii::$app->user->can('student') AND Yii::$app->user->id == $model->student_id) OR (Yii::$app->user->can('teacher') AND isset($tsg))) {
                if ($model->save()) {
                    Yii::$app->session->setFlash('success', 'Изменения сохранены');
                    $model->sendNotification();
                    return $this->render('view', ['id' => $model->id]);
                }
            } else
                throw new HttpException(403, 'У вас нет доступа к данной работе');
        }
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDownload($filename)
    {
        $labs = LabsStudents::find()->where('file = :file', [':file' => $filename])->one();

        if(!isset($labs))
            throw new HttpException(404, 'Файл не найден');
        if(Yii::$app->user->can('teacher')) {
            $tsg = TeacherSubjectGroups::find()->innerJoinWith(['subjectBranches', 'subjectBranches.branch', 'subjectBranches.branch.groups'])->where('teacher_subject_branch.id = :tsg AND teacher_subject_branch.teacher_id = :teacher AND groups.id = :group', [':teacher' => Yii::$app->user->id, ':group' => $labs->labs->group_id, ':tsg' => $labs->labs->tsg_id]);
        }
        if((Yii::$app->user->can('student') AND Yii::$app->user->id == $labs->student_id) OR (Yii::$app->user->can('teacher') AND isset($tsg)))
            Yii::$app->response->sendFile(Yii::getAlias('@webroot') . '/uploads/labs_students/' . $filename);
        else
            throw new HttpException(403, 'У вас нет доступа к данной работе');
    }

    /**
     * Deletes an existing LabsStudents model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if(Yii::$app->user->can('teacher')) {
            $tsg = TeacherSubjectGroups::find()->innerJoinWith(['subjectBranches', 'subjectBranches.branch', 'subjectBranches.branch.groups'])->where('teacher_subject_branch.id = :tsg AND teacher_subject_branch.teacher_id = :teacher AND groups.id = :group', [':teacher' => Yii::$app->user->id, ':group' => $model->labs->group_id, ':tsg' => $model->labs->tsg_id]);
            if(!isset($tsg))
                throw new \HttpException(403, 'У вас нет доступа к данной работе');
        }
        if($model->delete())
            Yii::$app->session->setFlash('success', 'Работа удалена');

        return $this->redirect(['index']);
    }

    /**
     * Finds the LabsStudents model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return LabsStudents the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = LabsStudents::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/labs-students/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use yii\helpers\ArrayHelper;
use app\models\Labs;
use app\models\LabsStudents;


/* @var $this yii\web\View */
/* @var $model app\models\LabsStudents */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="labs-students-form">

    <?php $form = ActiveForm::begin(['options'=>['enctype'=>'multipart/form-data']]); ?>

    <?php if(Yii::$app->user->can('student')): ?>
    <?php if($model->isNewRecord): ?>
    <?= $form->field($model, 'labs_id')->dropDownList(LabsStudents::getLabsAvailableSender()) ?>
    <?php else: ?>
    <?= $form->field($model, 'labs_id')->dropDownList(ArrayHelper::map(Labs::find()->with('labsStudents')->where('group_id = :group', [':group' => Yii::$app->user->identity->profile->group->id])->all(), 'id', 'title')) ?>
    <?php endif; ?>
    <?php endif; ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6])->label('Описание (примечание)') ?>

    <?php if(Yii::$app->user->can('student')): ?>
    <?= $form->field($model, 'attachFile')->widget(FileInput::className(), [
        'options'=> [],
        'pluginOptions'=>[
            'allowedFileExtensions'=>['jpg', 'jpeg', 'png', 'doc','docx','xls', 'xlsx', 'ppt', 'pptx', 'rar', 'zip', 'txt', 'odt', 'pdf', 'djvu'],
            'showCaption' => true,
            'showRemove' => true,
            'showUpload' => false,
            'showPreview' => true,
        ],
    ]);
    ?>
    <?php endif; ?>

    <?php if(Yii::$app->user->can('teacher') AND !$model->points): ?>
    <?= $form->field($model, 'points')->textInput()->label('баллы за работу') ?>
    <?php endif; ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Сохранить' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/labs-students/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\LabsStudentsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="labs-students-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'labs_id') ?>

    <?= $form->field($model, 'student_id') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'file') ?>

    <?php // echo $form->field($model, 'points') ?>

    <?php // echo $form->field($model, 'create_at') ?>

    <?php // echo $form->field($model, 'update_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Поиск', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Сброс', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/labs-students/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\LabsStudents */

$this->title = 'Добавление лабораторной работы для проверки';
$this->params['breadcrumbs'][] = ['label' => 'Лабораторные работы студентов', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="labs-students-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/labs-students/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\LabsStudentsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Лабораторные работы студентов';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="labs-students-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?php if(Yii::$app->user->can('student')): ?>
    <p>
        <?= Html::a('Добавить лабораторную работу для проверки', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?php endif; ?>
    <div class="labs-students-table table-responsive">
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'label' => 'специальность',
                'attribute' => 'planBranch',
                'value' => 'labs.tsg.subjectBranch.branch.title',
            ],
            [
                'label' => 'дисциплина',
                'attribute' => 'planSubject',
                'value' => 'labs.tsg.subjectBranch.subject.title',
            ],
            [
                'label' => 'год',
                'attribute' => 'year',
                'value' => 'labs.tsg.year',
            ],
            [
                'label' => 'семестр',
                'attribute' => 'sem',
                'value' => 'labs.tsg.sem',
            ],
            [
                'label' => 'Лабораторная работа',
                'attribute' => 'labs',
                'value' => 'labs.title',
            ],
            'description:ntext',
            [
                'label' => 'группа',
                'attribute' => 'groupTitle',
                'value' => 'labs.group.title',
                'visible' => Yii::$app->user->can('teacher') ? true : false,
            ],
            [
                'label' => 'студент',
                'attribute' => 'student',
                'value' => 'student.shortFio',
                'visible' => Yii::$app->user->can('teacher') ? true : false,
            ],
            [
                'label' => 'преподаватель',
                'attribute' => 'planTeacher',
                'value' => 'labs.tsg.teacher.shortFio',
                'visible' => Yii::$app->user->can('student') ? true : false,
            ],
            [
                'label' => 'Статус',
                'format' => 'raw',
                'attribute' => 'points',
                'value' => function($model) {
                    return ($model->points) ? 'Принята<br>(' . $model->points . ' баллов)' : 'Не принята';
                },
                'visible' => Yii::$app->user->can('teacher') ? true : false,
            ],
            //'file',
            // 'points',
            // 'create_at',
            // 'update_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    </div>

</div>

views/labs-students/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\LabsStudents */

$this->title = 'Редактирование л/р: ' . ' ' . $this->title = $model->labs->tsg->planTeacherWithTime . ' | ' . $model->student->shortFio;
$this->params['breadcrumbs'][] = ['label' => 'Л/р студентов', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $this->title = $model->labs->tsg->planTeacherWithTime . ' | ' . $model->labs->title . ' | ' . $model->student->shortFio, 'url' => ['view', 'id' => $model->id]];
?>
<div class="labs-students-update">

    <h1><?= $this->title = $model->labs->tsg->planTeacherWithTime . '<br><hr>' . $model->labs->title . (Yii::$app->user->can('teacher') ? ' | ' . $model->student->shortFio : '') ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/labs-students/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\LabsStudents */

$this->title = $model->labs->tsg->planTeacherWithTime . ' | ' . $model->labs->title;
$this->params['breadcrumbs'][] = ['label' => 'Лабораторные работы студентов', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="labs-students-view">

    <h1><?= $model->labs->tsg->planTeacherWithTime . '<br><hr>' . $model->labs->title; ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'labs.title',
            [
                'label' => 'Студент',
                'attribute' => 'student.shortFio',
                'visible' => Yii::$app->user->can('teacher')
            ],
            'description:ntext',
            [
                'attribute' => 'file',
                'format' => 'raw',
                'value' => (isset($model->file) AND file_exists(Yii::getAlias('@webroot') . '/uploads/labs_students/' . $model->file)) ? Html::a('Cкачать' . ' ['. $model->file .']', [\yii\helpers\Url::to('labs-students/download'), 'filename' => $model->file]) : 'Нет',
            ],            [
                'label' => 'Статус работы',
                'attribute' => 'points',
                'value' => ($model->points) ? 'Принята (' . $model->points . ' баллов)' : 'Не принята'
            ],
            [
                'label' => 'Дата добавления',
                'attribute' => 'create_at',
                'value' => Yii::$app->formatter->asDatetime($model->create_at, 'php:d-m-Y H:i:s', 'date')
            ],
            [
                'label' => 'Дата редактирования',
                'attribute' => 'update_at',
                'value' => Yii::$app->formatter->asDatetime($model->update_at, 'php:d-m-Y H:i:s', 'date')
            ],
        ],
    ]) ?>
    <?php if(Yii::$app->user->can('teacher') AND !$model->points): ?>
    <?php $form = ActiveForm::begin(['action' => ['labs-students/update', 'id' => $model->id]]); ?>
        <?= $form->field($model, 'points')->textInput()->label('Баллы за работу') ?>
        <div class="form-group">
            <?= Html::submitButton('Принять работу', ['class' => 'btn btn-success']) ?>
        </div>
    <?php ActiveForm::end(); ?>
    <?php endif; ?>
</div>