models/Journal.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;


/**
 * This is the model class for table "journal".
 *
 * @property integer $id
 * @property integer $tsg_id
 * @property string $description
 * @property integer $create_at
 * @property integer $update_at
 *
 * @property JournalRecords[] $journalRecords
 * @property TeacherSubjectGroups[] $tsg
 */
class Journal extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public $year;
    public $sem;
    public $planBranch;
    public $planSubject;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'journal';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tsg_id'], 'required'],
            ['tsg_id', 'unique', 'message' => 'вы уже завели журнал на эту дисциплину'],
            [['tsg_id', 'create_at', 'update_at', 'year', 'sem', 'planBranch', 'planSubject'], 'integer'],
            [['description'], 'string']
        ];
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['create_at', 'update_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['update_at'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tsg_id' => 'Специальность / Дисциплина (по плану)',
            'description' => 'Описание',
            'year' => 'год',
            'sem' => 'семестр',
            'create_at' => 'Дата',
            'update_at' => 'Update At',
            'planBranch' => 'Специальность',
            'planSubject' => 'Предмет' ,
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJournalRecords()
    {
        return $this->hasMany(JournalRecords::className(), ['journal_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTsg()
    {
        return $this->hasOne(TeacherSubjectGroups::className(), ['id' => 'tsg_id']);
    }
}

controllers/JournalController.php
<?php

namespace app\controllers;

use app\models\Groups;
use app\models\JournalRecords;
use app\models\Students;
use app\models\TeacherSubjectGroups;
use Yii;
use app\models\Journal;
use app\models\search\JournalSearch;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;


/**
 * JournalController implements the CRUD actions for Journal model.
 */
class JournalController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Journal models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new JournalSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Journal model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id, $group)
    {
        $journal = Journal::find()->where('id = :id', [':id' => $id])->one();
        if(!isset($journal))
            throw new HttpException(404, 'Журнал не найден');
        $groupModel = Groups::find()->joinWith(['branch', 'branch.subjectBranches'])->where('groups.id = :group', [':group' => $group])->one();
        if(!isset($groupModel))
            throw new HttpException(404, 'Нет такой группы');
        $tsgModel = TeacherSubjectGroups::find()->joinWith(['subjectBranches', 'subjectBranches.branch', 'subjectBranches.branch.groups'])->where('teacher_subject_branch.id = :tsg AND teacher_subject_branch.teacher_id = :teacher AND groups.id = :group', [':teacher' => Yii::$app->user->id, ':group' => $group, ':tsg' => $journal->tsg_id]);
        if(!isset($tsgModel))
            throw new HttpException(403, 'У вас недостаточно прав для доступа к этому журналу');
        $journalRecords = JournalRecords::find()->joinWith(['journal', 'journal.tsg'])->where('journal_id = :journal AND group_id = :group', [':journal' => $journal->id, ':group' => $group])->orderBy('date ASC')->all();
        $students = Students::find()->where('group_id = :group', [':group' => $group])->orderBy('lname')->all();
        /*$dataProvider = new ActiveDataProvider([
            'query' => JournalRecords::find()->where('journal_id = :journal AND group_id = :group', [':journal' => $journal->id, ':group' => $group])->orderBy('date ASC'),
        ]);*/
        return $this->render('view', [
            'model' => $journal,
            'students' => $students,
            'records' => $journalRecords,
            'group' => $groupModel,
            //'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Journal model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Journal();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Journal model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Journal model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Journal model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Journal the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Journal::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/journal/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\TeacherSubjectGroups;


/* @var $this yii\web\View */
/* @var $model app\models\Journal */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="journal-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'tsg_id')->dropDownList(ArrayHelper::map(TeacherSubjectGroups::find()->where('teacher_id = :teacher', [':teacher' => Yii::$app->user->id])->all(), 'id', 'planTeacherWithTime'), ['prompt'=>'Нет']); ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/journal/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\JournalSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="journal-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'teacher_id') ?>

    <?= $form->field($model, 'year') ?>

    <?= $form->field($model, 'sem') ?>

    <?= $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'create_at') ?>

    <?php // echo $form->field($model, 'update_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Поиск', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Сброс', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/journal/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Journal */

$this->title = 'Новый журнал';
$this->params['breadcrumbs'][] = ['label' => 'Журналы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="journal-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/journal/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\JournalSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $model \app\models\Journal */

$this->title = 'Журналы';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="journal-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Добавить журнал', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            /*'tsg.planTeacherWithTime',*/
            [
                'attribute' => 'planBranch',
                'value' => 'tsg.subjectBranch.branch.title',
            ],
            [
                'attribute' => 'planSubject',
                'value' => 'tsg.subjectBranch.subject.title',
            ],
            [
                'attribute' => 'year',
                'value' => 'tsg.year',
            ],
            [
                'attribute' => 'sem',
                'value' => 'tsg.sem',
            ],

            //'description:ntext',
            // 'create_at',
            // 'update_at',
            [
                'label' => 'Просмотр',
                'format' => 'raw',
                'value' => function($model) {
                    $result = '';
                    foreach ($model->tsg->subjectBranch->branch->groups as $group) {
                        $result .= Html::a($group->title, [Url::to('/journal/view'), 'id' => $model->id, 'group' => $group->id], ['target' => 'blank']) . '<br>';
                    }
                    return !empty($result) ? $result : '';
                }
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update}{delete}'
            ],
        ],
    ]); ?>

</div>

views/journal/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Journal */

$this->title = 'Update Journal: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Journals', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="journal-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/journal/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use kartik\grid\GridView;
use app\widgets\JournalWidget;
use kartik\date\DatePicker;


/* @var $this yii\web\View */
/* @var $model app\models\Journal */
/* @var $group app\models\Groups */

$this->title = $model->tsg->planTeacherWithTime . ' Группа: ' . $group->title;
$this->params['breadcrumbs'][] = ['label' => 'Журналы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$this->registerCssFile('//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css');
$this->registerJsFile('//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js',
    ['depends' => [
        'yii\web\YiiAsset',
        'yii\web\JqueryAsset'],
        'position' => \yii\web\View::POS_HEAD,
    ]);
$this->registerJsFile('//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js',
    ['depends' => [
        'yii\web\YiiAsset',
        'yii\web\JqueryAsset'],
        'position' => \yii\web\View::POS_HEAD,
    ]);
$this->registerJs("
//$.noConflict();
$('.journal-values tr td.value').editable({
    emptytext: '',
    type: 'text',
    pk: 1,
    params: function(params) {  //params already contain `name`, `value` and `pk`
        var data = {};
        data['record'] = $(this).attr('record');
        data['group'] = $(this).attr('group');
        data['year'] = $(this).attr('year');
        data['month'] = $(this).attr('month');
        data['day'] = $(this).attr('day');
        data['student'] = $(this).attr('student');
        data['journal'] = $(this).attr('journal');
        data['value'] = params['value'];
        return data;
    },
    url:   '/journal-records/update',
    title: 'Введите значение',

});

", \yii\web\View::POS_READY);
?>



<div class="journal-view table">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="row">
    <div class="col-lg-3 col-md-3 col-xs-4 col-sm-12">
    <p><strong>Быстый переход</strong></p>
    <?=  DatePicker::widget([
        'name' => 'check_issue_date',
        'value' => date('d-M', strtotime('+2 days')),
        'options' => ['placeholder' => 'Select issue date ...'],
        'pluginOptions' => [
            'format' => 'dd-M',
            'todayHighlight' => true,
            'changeYear' => false,
            //'viewMode' => "decades, years, months','days",
            //'minViewMode' => 'months',
            'language' => 'ru',
        ],
        'pluginEvents' => [
            /*"show" => "function(e) {  # `e` here contains the extra attributes }",
            "hide" => "function(e) {  # `e` here contains the extra attributes }",
            "clearDate" => "function(e) {  # `e` here contains the extra attributes }",*/
            "changeDate" => "function(e) {
             var month = e.date.getMonth() + 1;
             console.log(e.date);
             console.log(e.date.getDate());
             console.log(month);
             $('.table-responsive').scrollTo('td[month=\"' + month + '\"][day= \"' + e.date.getDate() + '\"]', 800);

             }",
            /*"changeYear" => "function(e) {  # `e` here contains the extra attributes }",
            "changeMonth" => "function(e) {  # `e` here contains the extra attributes }",*/
        ],
    ]); ?>
    </div>
    </div>
    <br>
    <?= JournalWidget::widget(['students' => $students, 'journal' => $model, 'journalRecords' => $records, 'group' => $group->id]) ?>
    <hr>
    <p>Примечание:</p>
    <?= Html::encode($model->description) ?>
</div>