models/Messages.php
<?php

namespace app\models;

use app\behaviors\FileUploadBehavior;
use Yii;
use app\models\user\User;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\HttpException;

/**
 * This is the model class for table "messages".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $user_from
 * @property integer $user_to
 * @property string $subject
 * @property string $body
 * @property string $file
 * @property integer $create_at
 * @property integer $update_at
 *
 * @property User $userFrom
 * @property User $userTo
 */
class Messages extends \yii\db\ActiveRecord
{

    /** @inheritdoc */
    public $attachFile;

    /** @inheritdoc */
    public $fileName;

    /** @inheritdoc */
    public $teachersTo;

    /** @inheritdoc */
    public $studentsTo;

    /** @inheritdoc */
    public $groupsTo;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'messages';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['create_at', 'update_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['update_at'],
                ],
            ],
            'fileUpload' => [
                'class' => FileUploadBehavior::className(),
                'image' => 'attachFile',
                'image_attribute' => 'file',
                'fileName' => 'fileName',
                'deleteFile' => false,
                'path' => '/web/uploads/personal_message/',
                //'resize'=>['height'=>300],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_from', 'user_to', 'subject', 'body'], 'required'],
            [['user_from', 'user_to', 'user_id', 'create_at', 'update_at'], 'integer'],
            [['body'], 'string'],
            [['teachersTo', 'studentsTo', 'groupsTo'], 'safe'],
            [['attachFile'], 'file', 'extensions'=>'jpg, jpeg, png, doc, docx, xls, xlsx, ppt, pptx, rar, zip, txt, odt, pdf, djvu', 'skipOnEmpty'=>true],
            [['subject', 'file', 'fileName'], 'string', 'max' => 128],
            [['groupsTo', 'teachersTo', 'studentsTo'], 'required', 'when' => function($model) {
                return (empty($model->studentTo) && empty($model->teachersTo) && empty($model->groupsTo));
            }, 'whenClient' => "function (attribute, value) {

                    if($('.field-messages-studentsto ul li.select2-selection__choice').attr('title') === undefined && $('.field-messages-teachersto ul li.select2-selection__choice').attr('title') === undefined && $('.field-messages-groupsto ul li.select2-selection__choice').attr('title') === undefined){
                        $('.field-messages-studentsto, .field-messages-teachersto, .field-messages-groupsto').removeClass( 'has-success' ).addClass( 'has-error' ).find('.help-block').text( 'Необходимо выбрать хотя бы одного получателя из любого списка');
                        return true;
                    } else {
                        $('.field-messages-studentsto, .field-messages-teachersto, .field-messages-groupsto').removeClass( 'has-error' ).find('.help-block').text('');
                        return false;
                    }
                }", 'message' => 'Необходимо выбрать хотя бы одного получателя из любого списка', 'on' => 'create'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'Пользователь',
            'user_from' => 'Отправитель',
            'user_to' => 'Получатель',
            'subject' => 'Тема',
            'body' => 'Сообщение',
            'file' => 'Файл',
            'teachersTo' => 'Преподаватели',
            'groupsTo' => 'Группы студентов',
            'studentsTo' => 'Отдельные студенты',
            'attachFile' => 'Файл',
            'create_at' => 'Дата',
            'update_at' => 'Update At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserFrom()
    {
        return $this->hasOne(User::className(), ['id' => 'user_from']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserTo()
    {
        return $this->hasOne(User::className(), ['id' => 'user_to']);
    }

    /** @inheritdoc */
    public function sendMessageGroups($groups)
    {
        $userFrom = User::findOne(['id' => Yii::$app->user->id]);
        foreach ($groups as $group) {
            $groupModel = Groups::find()->joinWith(['students', 'students.user'])->where('id = :group', [':group' => $group]);
            foreach ($groupModel->students as $student) {
                $this->sendPM($userFrom, $student);
            }
        }
    }

    /** @inheritdoc */
    public function sendMessageStudents($students)
    {
        $userFrom = User::findOne(['id' => Yii::$app->user->id]);
        foreach ($students as $student) {
            $this->sendPM($userFrom, $student);
        }
    }

    /** @inheritdoc */
    public function sendMessageTeachers($teachers)
    {
        $userFrom = User::findOne(['id' => Yii::$app->user->id]);
        foreach ($teachers as $teacher) {
            $this->sendPM($userFrom, $teacher);
        }
    }

    /** @inheritdoc */
    public function saveMessage($users, $fileName = false)
    {

        foreach($users as $user)
        {
            if($user == Yii::$app->user->id)
                continue;
            $messageFrom = new Messages();
            $messageTo = new Messages();

            $messageFrom->user_from = Yii::$app->user->id;
            if($fileName) {
                $messageFrom->fileName = $fileName;
                $messageTo->fileName = $fileName;
            }

            $messageFrom->user_to = $user;
            $messageFrom->subject = $this->subject;
            $messageFrom->body = $this->body;
            $messageFrom->user_id = $messageFrom->user_from;

            $messageTo->user_from = Yii::$app->user->id;
            $messageTo->user_to = $user;
            $messageTo->subject = $this->subject;
            $messageTo->body = $this->body;
            $messageTo->user_id = $messageTo->user_to;
            if(!$messageFrom->save())
            {
                throw new HttpException(500, 'При сохранении сообщения произошла ошибка');
            }
            if(!$messageTo->save())
            {
                throw new HttpException(500, 'При сохранении сообщения произошла ошибка');
            }
        }
    }

    private function sendPM($userFrom, $userTo)
    {
        Yii::$app->mailer->compose('messages/new-message', ['from' => $userFrom, 'user' => $userTo])
            ->setFrom('admin@kafedra.dev')
            ->setTo($userTo->user->email)
            ->setSubject('Новое сообщение на сайте кафедры Вычислительной техники')
            ->send();
    }


    public static function truncation($str, $length)
    {
        $str=substr($str, 0, $length-2);        //Обрезаем до заданной длины
        $words=explode(" ", $str);                //Разбиваем по словам
        array_splice($words,-1);                //Удаляем последнее слово

        $last=array_pop($words);                //Получаем последнее слово

        for ($i=1; $i<strlen($last); $i++) {
            //Ищем и удаляем в конце последнего слова все кроме букв и цифр
            if (preg_match('/\W$/',substr($last,-1,1))) $last=substr($last,0,strlen($last)-1);
            else break;
        }
        return implode(" ", $words).' '.$last.'...';
    }

}

controllers/MessagesController.php
<?php

namespace app\controllers;

use app\models\Groups;
use Yii;
use app\models\Messages;
use app\models\search\MessagesSearch;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
/**
 * MessagesController implements the CRUD actions for Messages model.
 */
class MessagesController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Messages models.
     * @return mixed
     */
    public function actionIndex()
    {
        /*$searchModel = new MessagesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);*/

        $dataProviderAll = new ActiveDataProvider([
            'query' => Messages::find()->where('(user_from = :user OR user_to = :user) AND user_id = :user', [':user' => Yii::$app->user->id])->orderBy('messages.id DESC'),
        ]);

        $dataProviderInbox = new ActiveDataProvider([
            'query' => Messages::find()->where('user_to = :user AND user_id = :user', [':user' => Yii::$app->user->id])->orderBy('messages.id DESC'),
        ]);

        /*foreach ($dataProviderInbox->models as $model) {
            if ($model->status == 0) {
                $model->status = 1;
                $model->update();
            }
        }*/

        $dataProviderOutbox = new ActiveDataProvider([
            'query' => Messages::find()->where('user_from = :user AND user_id = :user', [':user' => Yii::$app->user->id])->orderBy('messages.id DESC'),
        ]);


        return $this->render('index', ['dataProviderAll' => $dataProviderAll, 'dataProviderInbox' => $dataProviderInbox, 'dataProviderOutbox' => $dataProviderOutbox]);

    }

    /**
     * Displays a single Messages model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Messages model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Messages(['scenario' => 'create']);


        if ($model->load(Yii::$app->request->post())) {
            if(isset($_FILES['Messages']['name']['attachFile']));
                $fileName = Yii::$app->security->generateRandomString();
            if(is_array($model->teachersTo))
            {
                $model->saveMessage($model->teachersTo, $fileName);
            }
            if(is_array($model->groupsTo))
            {
                foreach ($model->groupsTo as $groups) {
                    $group = Groups::findOne(['id' => $groups]);
                    if(isset($group) AND isset($groups->students))
                        $model->saveMessage($groups->students, $fileName);
                }
            }
            if(is_array($model->studentsTo))
            {
                $model->saveMessage($model->studentsTo, $fileName);
            }
            Yii::$app->session->setFlash('success', 'Сообщение успешно отправлено');
                return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionDownload($filename)
    {
        $message = Messages::find()->where('file = :file AND (user_from = :user OR user_to = :user)', [':file' => $filename, ':user' => Yii::$app->user->id])->one();
        if(!isset($message))
            throw new HttpException(404, 'Файл не найден');
        Yii::$app->response->sendFile(Yii::getAlias('@webroot') . '/uploads/personal_message/' . $filename);
    }

    /**
     * Updates an existing Messages model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Messages model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Messages model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Messages the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Messages::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/messages/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use app\models\Students;
use app\models\Teachers;
use app\models\Groups;

/* @var $this yii\web\View */
/* @var $model app\models\Messages */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="messages-form">

    <?php $form = ActiveForm::begin(
        [
            'options'=>['enctype'=>'multipart/form-data'],
            'enableAjaxValidation' => false,
            'enableClientValidation' => true,
        ]
    ); ?>

    <?= $form->field($model, 'teachersTo')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(Teachers::find()->where('user_id != :user', [':user' => Yii::$app->user->id])->all(), 'user_id', 'shortFio'),
        'options' => ['placeholder' => 'Выберите получателя ...', 'multiple' => true],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); ?>


    <?= $form->field($model, 'groupsTo')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(Groups::find()->all(), 'id', 'title'),
        'options' => ['placeholder' => 'Выберите получателя ...', 'multiple' => true],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); ?>

    <?= $form->field($model, 'studentsTo')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(Students::find()->where('user_id != :user', [':user' => Yii::$app->user->id])->all(), 'user_id', 'shortFio'),
        'options' => ['placeholder' => 'Выберите получателя ...', 'multiple' => true],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); ?>

    <?= $form->field($model, 'subject')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'attachFile')->widget(FileInput::className(), [
        'options'=> [],
        'pluginOptions'=>[
            'allowedFileExtensions'=>['jpg', 'jpeg', 'png', 'doc','docx','xls', 'xlsx', 'ppt', 'pptx', 'rar', 'zip', 'txt', 'odt', 'pdf', 'djvu'],
            'showCaption' => true,
            'showRemove' => true,
            'showUpload' => false,
            'showPreview' => true,
        ],
    ]);
    ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Сохранить' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/messages/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\MessagesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="messages-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'user_from') ?>

    <?= $form->field($model, 'user_to') ?>

    <?= $form->field($model, 'subject') ?>

    <?php // echo $form->field($model, 'body') ?>

    <?php // echo $form->field($model, 'file') ?>

    <?php // echo $form->field($model, 'create_at') ?>

    <?php // echo $form->field($model, 'update_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Поиск', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Сброс', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/messages/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Messages */

$this->title = 'Новое сообщение';
$this->params['breadcrumbs'][] = ['label' => 'Сообщения', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="messages-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/messages/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\bootstrap\Tabs;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\MessagesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Сообщения';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php
foreach(Yii::$app->session->getAllFlashes() as $key => $message) {
    echo '<div role="alert" class="alert alert-' . $key . '">' . $message . "</div>\n";
}
?>
<div class="messages-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Написать сообщение', ['create'], ['class' => 'btn btn-success']) ?>
    </p>


            <?=  Tabs::widget([
                'items' => [
                    [
                        'label' => 'Все сообщения',
                        'content' => GridView::widget([
                            'dataProvider' => $dataProviderAll,
                            'layout'=>"{items}\n{pager}",
                            'columns' => [
                                [
                                    'label' => 'тема',
                                    'value' => 'subject',
                                ],
                                [
                                    'label' => 'сообщение',
                                    'value' => function($model) {
                                    return \app\models\Messages::truncation($model->body, 100);
                                }
                                ],
                                [
                                    'label' => 'отправитель',
                                    'value' => function($model) {
                                        return ($model->userFrom->id == Yii::$app->user->id) ? 'Вы' : $model->userFrom->username;
                                    }
                                ],
                                [
                                    'label' => 'получатель',
                                    'value' => function($model) {
                                        return ($model->userTo->id == Yii::$app->user->id) ? 'Вы' : $model->userTo->username;
                                    }
                                ],
                                [
                                    'label' => 'дата',
                                    'value' => function ($model) { return Yii::$app->formatter->asDatetime($model->create_at, 'php:d-m-Y H:i:s', 'date'); }
                                ],
                                [
                                    'class' => 'yii\grid\ActionColumn',
                                    'template' => '{view} {delete}',
                                ],
                            ],
                        ]),
                        'active' => true,
                        'headerOptions' => [],
                        'options' => ['id' => 'messageAll'],
                    ],
                    [
                        'label' => 'Входящие',
                        'content' => GridView::widget([
                            'dataProvider' => $dataProviderInbox,
                            'layout'=>"{items}\n{pager}",
                            'columns' => [
                                [
                                    'label' => 'тема',
                                    'value' => 'subject',
                                ],
                                [
                                    'label' => 'сообщение',
                                    'value' => 'body',
                                ],
                                [
                                    'label' => 'отправитель',
                                    'value' => function($model) {
                                        return ($model->userFrom->id == Yii::$app->user->id) ? 'Вы' : $model->userFrom->username;
                                    }
                                ],
                                [
                                    'label' => 'получатель',
                                    'value' => function($model) {
                                        return ($model->userTo->id == Yii::$app->user->id) ? 'Вы' : $model->userTo->username;
                                    }
                                ],
                                [
                                    'label' => 'дата',
                                    'value' => function ($model) { return Yii::$app->formatter->asDatetime($model->create_at, 'php:d-m-Y H:i:s', 'date'); }
                                ],
                                [
                                    'class' => 'yii\grid\ActionColumn',
                                    'template' => '{view} {delete}',
                                ],
                            ],
                        ]),
                        'headerOptions' => [],
                        'options' => ['id' => 'messageInbox'],
                    ],
                    [
                        'label' => 'Исходящие',
                        'content' => GridView::widget([
                            'dataProvider' => $dataProviderOutbox,
                            'layout'=>"{items}\n{pager}",
                            'columns' => [
                                [
                                    'label' => 'тема',
                                    'value' => 'subject',
                                ],
                                [
                                    'label' => 'сообщение',
                                    'value' => 'body',
                                ],
                                [
                                    'label' => 'отправитель',
                                    'value' => function($model) {
                                        return ($model->userFrom->id == Yii::$app->user->id) ? 'Вы' : $model->userFrom->username;
                                    }
                                ],
                                [
                                    'label' => 'получатель',
                                    'value' => function($model) {
                                        return ($model->userTo->id == Yii::$app->user->id) ? 'Вы' : $model->userTo->username;
                                    }
                                ],
                                [
                                    'label' => 'дата',
                                    'value' => function ($model) { return Yii::$app->formatter->asDatetime($model->create_at, 'php:d-m-Y H:i:s', 'date'); }
                                ],
                                [
                                    'class' => 'yii\grid\ActionColumn',
                                    'template' => '{view} {delete}',
                                ],
                            ],

                        ]),
                        'headerOptions' => [],
                        'options' => ['id' => 'messageOutbox'],
                    ],
                ],
            ]);
            ?>


</div>

views/messages/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Messages */

$this->title = 'Редактирование сообщения: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Messages', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="messages-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/messages/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Messages */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Сообщения', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="messages-view">
    <p>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы действительно хотите удалить данное сообщение?',
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            [
                'label' => 'отправитель',
                'value' => ($model->userFrom->id == Yii::$app->user->id) ? 'Вы' : $model->userFrom->username,
            ],
            [
                'label' => 'получатель',
                'value' => ($model->userTo->id == Yii::$app->user->id) ? 'Вы' : $model->userTo->username,
            ],
            'subject',
            'body:ntext',
            [
                'attribute' => 'file',
                'format' => 'raw',
                'value' => (isset($model->file) AND file_exists(Yii::getAlias('@webroot') . '/uploads/personal_message/' . $model->file)) ? Html::a('Cкачать' . ' ['. $model->file .']', [\yii\helpers\Url::to('messages/download'), 'filename' => $model->file]) : 'Нет',
                //'value' => Yii::getAlias('@webroot') . '/uploads/personal_message/' . $model->file,
            ],
            [
                'attribute' => 'create_at',
                'value' => Yii::$app->formatter->asDatetime($model->create_at, 'php:d-m-Y H:i:s', 'date')
            ],
            //'update_at',
        ],
    ]) ?>

</div>