models/Cworks.php
<?php

namespace app\models;

use app\models\search\CworksDefaultSearch;
use app\models\search\CworksSearch;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\db\ActiveRecord;
use yii\web\HttpException;

/**
 * This is the model class for table "cworks".
 *
 * @property integer $id
 * @property integer $tsg_id
 * @property integer $student_id
 * @property integer $cworks_default_id
 * @property integer $status_id
 * @property string $ptitle
 * @property string $source_data
 * @property string $calculation_part
 * @property string $graphic_part
 * @property string $exper_part
 * @property string $start_at
 * @property string $finish_at
 * @property integer $create_at
 * @property integer $update_at
 *
 * @property integer STATUS_ADDED
 * @property integer STATUS_WAITING_FOR_CONFIRM
 * @property integer STATUS_CONFIRM_TEACHER
 * @property integer STATUS_CONFIRM_ZAVKAF
 * @property integer STATUS_REJECTED
 *
 * @property CworksDefault $cworksDefault
 * @property Students $student
 * @property TeacherSubjectGroups $tsg
 */
class Cworks extends \yii\db\ActiveRecord
{

    const STATUS_ADDED = 0;
    const STATUS_WAITING_FOR_CONFIRM = 1;
    const STATUS_CONFIRM_TEACHER = 2;
    const STATUS_CONFIRM_ZAVKAF = 3;
    const STATUS_REJECTED = 4;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cworks';
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tsg_id', 'cworks_default_id', 'ptitle', 'source_data', 'calculation_part', 'graphic_part', 'start_at'], 'required'],
            [['id', 'tsg_id', 'student_id', 'cworks_default_id', 'status_id', 'create_at', 'update_at'], 'integer'],
            [['ptitle', 'source_data', 'calculation_part', 'graphic_part', 'exper_part'], 'string'],
            //[['finish_at'], 'validateToDates'],
            [['id'], 'unique'],
            [['create_at', 'update_at'], 'safe']
        ];
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['create_at', 'update_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['update_at'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tsg_id' => 'Преподаватель/Предмет',
            'student_id' => 'Студент',
            'cworks_default_id' => 'Шаблон',
            'status_id' => 'Статус',
            'ptitle' => 'Заголовок',
            'source_data' => 'Исходные данные',
            'calculation_part' => 'Расчетная часть',
            'graphic_part' => 'Графическая часть',
            'exper_part' => 'Экспериментальная часть',
            'start_at' => 'Дата получения задания',
            'finish_at' => 'Дата сдачи',
            'create_at' => 'Дата добавления',
            'update_at' => 'Дата изменения',
        ];
    }

    public function validateToDates($attribute, $params)
    {

        if($this->start_at  > $this->finish_at) {
            $this->addError($attribute, 'Дата получения позднее чем дата сдачи');
        }
        return true;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCworksDefault()
    {
        return $this->hasOne(CworksDefault::className(), ['id' => 'cworks_default_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudent()
    {
        return $this->hasOne(Students::className(), ['user_id' => 'student_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTsg()
    {
        return $this->hasOne(TeacherSubjectGroups::className(), ['id' => 'tsg_id']);
    }

    public function getStatus()
    {
        return array(
            self::STATUS_ADDED => 'Добавлено',
            self::STATUS_WAITING_FOR_CONFIRM => 'Ожидает проверки',
            self::STATUS_CONFIRM_TEACHER => 'Проверено преподавателем',
            self::STATUS_CONFIRM_ZAVKAF => 'Проверено заведующим кафедры',
            self::STATUS_REJECTED => 'Отклонено',
        );
    }

    public static function showView($status)
    {
        if (//(Yii::$app->user->can('admin') AND ($status != Cworks::STATUS_CONFIRM_TEACHER)) OR
            (Yii::$app->user->can('teacher') AND ($status != Cworks::STATUS_WAITING_FOR_CONFIRM)) OR
                (Yii::$app->user->can('student') AND ($status != Cworks::STATUS_CONFIRM_ZAVKAF)))
            return false;
        else
            return true;

    }

    /*public function exportWord()
    {
        $searchModel = new CworksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        var_dump(Yii::$app->request->queryParams);die;
        if(empty($dataProvider))
            throw new HttpException(404, 'Бланка с таким номером не существует');

        // Initalize the TBS instance
        $OpenTBS = new \hscstudio\export\OpenTBS; // new instance of TBS
        // Change with Your template kaka
        $template = Yii::getAlias('@web/uploads').'/cworks_templates/cworks_template.docx';
        $OpenTBS->LoadTemplate($template); // Also merge some [onload] automatic fields (depends of the type of document).
        //$OpenTBS->VarRef['modelName']= "Mahasiswa";
        $data = [];
        $no=1;
        foreach($dataProvider->getModels() as $mahasiswa){
            $data[] = [
                'no'=>$no++,
                'nama'=>$mahasiswa->nama,
                'nim'=>$mahasiswa->nim,
            ];
        }
        $OpenTBS->MergeBlock('data', $data);
        // Output the result as a file on the server. You can change output file
        $OpenTBS->Show(OPENTBS_DOWNLOAD, 'export.docx'); // Also merges all [onshow] automatic fields.
        exit;
    }*/
}

controllers/CworksController.php
<?php

namespace app\controllers;

use app\models\CworksDefault;
use app\models\Groups;
use app\models\Students;
use app\models\TeacherSubjectGroups;
use Yii;
use app\models\Cworks;
use app\models\search\CworksSearch;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use DateTime;
/**
 * CworksController implements the CRUD actions for Cworks model.
 */
class CworksController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'update', 'delete', 'view', 'export-word', 'update-default-list'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['reject', 'zav-kaf-confirm'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [
                        'actions' => ['create'],
                        'allow' => true,
                        'roles' => ['admin', 'student'],
                    ],
                    [
                        'actions' => ['reject', 'teacher-confirm'],
                        'allow' => true,
                        'roles' => ['teacher'],
                    ],
                    [
                        'actions' => ['send-for-confirm'],
                        'allow' => true,
                        'roles' => ['student'],
                    ],
                ]
            ]
        ];
    }

    /**
     * Lists all Cworks models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CworksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Cworks model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Cworks model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Cworks();
        if($model->load(Yii::$app->request->post()))
        {
            if(Yii::$app->user->can('student'))
                $model->student_id = Yii::$app->user->id;
        }
        if  ($model->save()) {
            Yii::$app->session->setFlash('success', 'Бланк на курсовое проектирование добавлен');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            if (Yii::$app->user->can('student')) {
                $student = Students::findOne(['user_id'=>Yii::$app->user->id]);
                return $this->render('create', [
                    'model' => $model, 'student' => $student,
                ]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
    }

    public function actionExportWord($id)
    {
        $id = (int)$id;
        //$model = new Cworks();
        $model = Cworks::findOne(['id'=>$id]);
        if(!isset($model))
            throw new HttpException(404, 'Бланка с таким номером не существует');
        //if(Yii::$app->user->can('admin') AND $model->status != Cworks::STATUS_CONFIRM_TEACHER)
            //throw new HttpException(403, 'Заведующему кафедры не доступны для просмотра и подтверждения бланки, которые не были проверены преподавателями');
        if(Yii::$app->user->can('teacher') AND $model->status_id != Cworks::STATUS_WAITING_FOR_CONFIRM)
            throw new HttpException(403, 'Преподавателям не доступны для просмотра и подтверждения бланки, которые не были переведены в статус "' . $model->getStatus()[$model->status_id] . '"');
        if(Yii::$app->user->can('student') AND $model->status_id != Cworks::STATUS_CONFIRM_ZAVKAF)
            throw new HttpException(403, 'Студентам не доступны для загрузки бланки, которые не были подтверждены препеподавателем и заведующим кафедры');
        if(Yii::$app->user->can('teacher') AND (Yii::$app->user->id != $model->tsg->teacher_id))
            throw new HttpException(403, 'Вы попытались загрузить бланк на курсовой проект, рукодителем которого не являетесь');
        if(Yii::$app->user->can('student') AND (Yii::$app->user->id != $model->student_id))
            throw new HttpException(403, 'Вы попытались открыть чужой бланк на курсовое проектирование');
        // Initalize the TBS instance
        $OpenTBS = new \hscstudio\export\OpenTBS; // new instance of TBS
        // Change with Your template kaka
        $template =  \Yii::getAlias('@webroot').'/uploads/cworks_templates/cworks_template.docx';

        $OpenTBS->LoadTemplate($template, OPENTBS_ALREADY_UTF8); // Also merge some [onload] automatic fields (depends of the type of document).

        $date = new DateTime($model->start_at);
        $start_cwork =  $date->format('d.m.y');
        $data = [
            'subject'=>$model->tsg->subjectBranch->subject->title,
            'stud_shortFio'=>$model->student->shortFio,
            'group'=>$model->student->group->title,
            'ptitle'=>$model->ptitle,
            'source_data'=>$model->source_data,
            'calculation_part'=>$model->calculation_part,
            'graphic_part'=>$model->graphic_part,
            'exper_part'=>$model->exper_part,
            'start_date'=>$start_cwork,
            'teacher_shortFio'=>$model->tsg->teacher->shortFio,
            'year'=>date('Y'),
        ];
        //var_dump($data['subject']);die;
        $OpenTBS->MergeField('data', $data);
        // Output the result as a file on the server. You can change output file
        $OpenTBS->Show(OPENTBS_DOWNLOAD, 'export.docx');
        exit;
    }

    /*public function actionAddBlank()
    {

    }*/

    public function actionSendForConfirm($id)
    {
        $id = (int)$id;
        $cwork = Cworks::findOne(array('id' => $id));
        if(!isset($cwork))
            throw new HttpException('404', 'Бланка таким номером не всуществует');
        if($cwork->student_id != Yii::$app->user->id)
            throw new HttpException('403', 'У вас нет доступа к бланку с таким номером');
        if($cwork->status_id != Cworks::STATUS_ADDED or $cwork->status_id == Cworks::STATUS_REJECTED)
            throw new HttpException('500', 'Данный бланк уже проверяется или был отклонен. Исправьте ошибки и снова отправьте его на проверку');
        $cwork->status_id = Cworks::STATUS_WAITING_FOR_CONFIRM;
        $cwork->update();
        Yii::$app->session->setFlash('success', 'Статус бланка был изменен. Бланк ожидает проверки преподавателем');
        $this->redirect('index');
    }

    public function actionTeacherConfirm($id)
    {
        $id = (int)$id;
        $cwork = Cworks::findOne(array('id' => $id));
        if(!isset($cwork))
            throw new HttpException('404', 'Бланка с таким номером не всуществует');
        if($cwork->status_id != Cworks::STATUS_WAITING_FOR_CONFIRM)
            throw new HttpException('500', 'Данный бланк не ожидает проверки преподавателем');
        if($cwork->tsg->teacher_id != Yii::$app->user->id)
            throw new HttpException('403', 'У вас нет прав на подтверждение данного бланка');
        $cwork->status_id = Cworks::STATUS_CONFIRM_TEACHER;
        $cwork->update();
        Yii::$app->session->setFlash('success', 'Статус бланка был изменен. Бланк ожидает проверки заведующим кафедрой');
        $this->redirect('index');
    }

    public function actionZavKafConfirm($id)
    {
        $id = (int)$id;
        $cwork = Cworks::findOne(array('id' => $id));
        if(!isset($cwork))
            throw new HttpException('404', 'Бланка с таким номером не всуществует');
        if($cwork->status_id != Cworks::STATUS_CONFIRM_TEACHER)
            throw new HttpException('500', 'Данный бланк не ожидает проверки заведующим кафедрой');
        $cwork->status_id = Cworks::STATUS_CONFIRM_ZAVKAF;
        $cwork->update();
        Yii::$app->session->setFlash('success', 'Статус бланка был изменен. Теперь студент сможет загрузить подтвержденный бланк');
        $this->redirect('index');
    }

    public function actionReject($id)
    {
        $id = (int)$id;
        $cwork = Cworks::findOne(array('id' => $id));
        if(!isset($cwork))
            throw new HttpException('404', 'Бланка с таким номером не всуществует');
        if($cwork->status_id == Cworks::STATUS_ADDED or $cwork->status_id == Cworks::STATUS_CONFIRM_ZAVKAF)
            throw new HttpException('500', 'Данный бланк не может быть отклонен, так как он не ожидает чьей либо проверки, либо уже был подтвержден заведующим кафедрой');
        if(Yii::$app->user->can('teacher') and $cwork->tsg->teacher_id != Yii::$app->user->id)
            throw new HttpException('403', 'у вас недостаточно прав для того, чтобы отклонить данный бланк');
        $cwork->status_id = Cworks::STATUS_REJECTED;
        $cwork->update();
        Yii::$app->session->setFlash('success', 'Статус бланка был изменен. Бланк был отклонен');
        $this->redirect('/cworks/index');

    }

    public function actionDownload($id)
    {
        /*...*/
    }

    public function actionUpdateDefaultList()
    {
        $id = (int)$_POST['id'];
        $countPosts = CworksDefault::find()
            ->where(['tsg_id' => $id])

views/cworks/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\Cworks */
/* @var $form yii\widgets\ActiveForm */
?>
<?php
$this->registerJs("
    if('".$this->context->action->id."' == 'update')
            $('.field-cworks-cworks_default_id').show();
    $('#cworks-tsg_id').on('change', function(){
        if($(this).val() !== '') {
        var id = $(this).val();
            $.ajax({
                type: 'POST',
                data : {'id':id},
                url: '/cworks/update-default-list',
                success: function(data){
                    var result = jQuery.parseJSON(data);
                    $('#cworks-cworks_default_id').html(result);
                    $('.field-cworks-cworks_default_id').show();
                }
            });
            return false;
        } else {
            $('.field-cworks-cworks_default_id').hide();
        }
    });
", \yii\web\View::POS_READY);
?>
<div class="cworks-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php if(!Yii::$app->user->can('student')): ?>
    <?= $form->field($model, 'tsg_id')->dropDownList(ArrayHelper::map(\app\models\TeacherSubjectGroups::find()->all(), 'id', 'planTeacher'), ['prompt'=>'Нет']); ?>
    <?php else: ?>
    <?= $form->field($model, 'tsg_id')->dropDownList(ArrayHelper::map(\app\models\TeacherSubjectGroups::find()->joinWith('subjectBranch')->where("`subject_branches`.`branch_id`=".Yii::$app->user->identity->profile->group->branch->id." AND (`subject_branches`.`course_work`=1 OR `subject_branches`.`course_project`=1) AND `subject_branches`.`year`=".date('Y'))->all(), 'id', 'planTeacher'), ['prompt'=>'Нет']); ?>
    <?php endif; ?>
    <?php if(!Yii::$app->user->can('student')): ?>
    <?= $form->field($model, 'student_id')->dropDownList(ArrayHelper::map(\app\models\Students::find()->all(), 'user_id', 'shortFio'), ['prompt'=>'Нет']); ?>
    <?php endif; ?>
    <?= $this->context->action->id == 'create' ?  $form->field($model, 'cworks_default_id')->dropDownList([items],[options], ['prompt'=>'Нет']) : $form->field($model, 'cworks_default_id')->dropDownList(ArrayHelper::map(\app\models\CworksDefault::findAll(['tsg_id'=>$model->tsg_id]), 'id', 'ptitle'), ['prompt'=>'Нет']); ?>

    <?= $form->field($model, 'ptitle')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'source_data')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'calculation_part')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'graphic_part')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'exper_part')->textarea(['rows' => 6]) ?>

    <?= $form->field($model,'start_at')->widget(DatePicker::className(),[
        'dateFormat' => 'yyyy-MM-dd',
        'clientOptions' => []
    ]) ?>
   <!-- --><?/*= $form->field($model,'finish_at')->widget(DatePicker::className(),[
        'dateFormat' => 'dd-MM-yyyy',
        'clientOptions' => []]) */?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Сохранить' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/cworks/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\CworksSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="cworks-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'tsg_id') ?>

    <?= $form->field($model, 'student_id') ?>

    <?= $form->field($model, 'cworks_default_id') ?>

    <?= $form->field($model, 'status_id') ?>

    <?php // echo $form->field($model, 'ptitle') ?>

    <?php // echo $form->field($model, 'source_data') ?>

    <?php // echo $form->field($model, 'calculation_part') ?>

    <?php // echo $form->field($model, 'graphic_part') ?>

    <?php // echo $form->field($model, 'exper_part') ?>

    <?php // echo $form->field($model, 'start_at') ?>

    <?php // echo $form->field($model, 'finish_at') ?>

    <?php // echo $form->field($model, 'create_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Поиск', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Сброс', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/cworks/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Cworks */

$this->title = 'Добавить бланк курсового проекта';
$this->params['breadcrumbs'][] = ['label' => 'Курсовое проектирование', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="cworks-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'student' => $student,
    ]) ?>

</div>

views/cworks/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\CworksSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Курсовое проектирование';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php
foreach(Yii::$app->session->getAllFlashes() as $key => $message) {
    echo '<div role="alert" class="alert alert-' . $key . '">' . $message . "</div>\n";
}
?>
<div class="cworks-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Добавить бланк на курсовое проектирование', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <div class="table-responsive">
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            [
                'label'=>'Студент',
                'attribute'=>'shortFio',
                'format' => 'raw',
                'value'=>function ($data) {
                    return Html::a($data->student->shortFio, '/students/view/'.$data->student_id, ['target' => '_blank']);
                },
            ],
            [
                'label'=>'__________Предмет/Преподаватель__________',
                'attribute'=> 'planTeacher',
                'value' => function ($data) {
                        return Html::a($data->tsg->planTeacher, '/tsg/view?id='.$data->tsg_id, ['target' => '_blank']);
                    },
                'format' => 'raw',
                'filter' => Html::activeDropDownList($searchModel, 'tsg', ArrayHelper::map(\app\models\TeacherSubjectGroups::find()->all(), 'id', 'planTeacher'),['class'=>'form-control','prompt' => 'Не выбрано']),
            ],
            [
                'label'=>'__________Название работы__________',
                'attribute'=>'ptitle',
                'format'=>'text',
                'value'=>'ptitle',
            ],
            [
                'label'=>'Статус',
                'attribute'=>'status_id',
                'value'=> function($data) {
                    return $data->getStatus()[$data->status_id];
                },
                'format'=>'raw',
                'filter'=>Html::activeDropDownList($searchModel, 'status_id', $searchModel->getStatus(), ['class'=>'form-control','prompt' => 'Не выбрано']),
            ],
            [
                'label'=>'__________Исходные данные__________',
                'attribute'=>'source_data',
                'value'=>'source_data',
            ],
            [
                'label'=>'__________Расчетная часть__________',
                'attribute'=>'calculation_part',
                'format'=>'text',
                'value'=>'calculation_part',
            ],
            [
                'label'=>'__________Графическая часть__________',
                'attribute'=>'calculation_part',
                'format'=>'text',
                'value'=>'graphic_part',
            ],
            [
                'label'=>'__________Экспериментальная часть__________',
                'attribute'=>'exper_part',
                'format'=>'text',
                'value'=>'exper_part',
            ],
             'start_at',
             'finish_at',
            [
                'attribute'=>'create_at',
                'value'=> function ($data) {
                    return Yii::$app->formatter->asDate($data['create_at'], 'medium');
                },
            ],
            [
                'attribute'=>'update_at',
                'value'=> function ($data) {
                    return Yii::$app->formatter->asDate($data['update_at'], 'medium');
                },
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    </div>
</div>

views/cworks/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Cworks */

$this->title = 'Редактирование бланка на курсовое проектирование: ' . ' ' . $model->ptitle;
$this->params['breadcrumbs'][] = ['label' => 'Курсовое проектирование', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->ptitle, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование бланка на КП';
?>
<div class="cworks-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/cworks/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Cworks */

$this->title = $model->ptitle;
$this->params['breadcrumbs'][] = ['label' => 'Курсовое проектирование', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<?php
foreach(Yii::$app->session->getAllFlashes() as $key => $message) {
    echo '<div role="alert" class="alert alert-' . $key . '">' . $message . "</div>\n";
}
?>
<div class="cworks-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы действительно хотите удалить этот бланк?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'cworksDefault.tsg.planTeacher',
            [
                'label' => 'Студент',
                'attribute' => 'student.shortFio',
            ],
            //'cworks_default_id',
            [
                'label'=>'Статус',
                'value'=>$model->getStatus()[$model->status_id],
            ],
            'ptitle:ntext',
            'source_data:ntext',
            'calculation_part:ntext',
            'graphic_part:ntext',
            'exper_part:ntext',
            'start_at',
            'finish_at',
            [
                'attribute'=>'create_at',
                'value'=>Yii::$app->formatter->asDate($model->create_at, 'medium'),
            ],
            [
                'attribute'=>'update_at',
                'value'=>Yii::$app->formatter->asDate($model->update_at, 'medium'),
            ],
        ],
    ]) ?>
    <?php if(Yii::$app->user->can('admin') and $model->status_id == $model::STATUS_CONFIRM_TEACHER): ?>
        <?= Html::a('Подтвердить', ['zav-kaf-confirm', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Отклонить', ['reject', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
    <?php endif; ?>

    <?php if(Yii::$app->user->can('teacher') and $model->status_id == $model::STATUS_WAITING_FOR_CONFIRM): ?>
        <?= Html::a('Подтвердить', ['teacher-confirm', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Отклонить', ['reject', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
    <?php endif; ?>
    <?php if(Yii::$app->user->can('student') and $model->status_id == $model::STATUS_ADDED): ?>
        <?= Html::a('Отправить на проверку', ['send-for-confirm', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
    <?php endif; ?>

    <?= (\app\models\Cworks::showView($model->status_id)) ? Html::a('Посмотреть/Сохранить в Word', ['/cworks/export-word', 'id'=>$model->id]) : ''; ?>
</div>